version: "3.9"

services:

  # Create service with RabbitMQ.
  sms-broker:
    image: rabbitmq:3-management-alpine
    container_name: sms-broker
    ports:
      - 5672:5672 # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI
    volumes:
      - ./data:/var/lib/rabbitmq
      - ./log:/var/log/rabbitmq
    restart: always
    networks:
      - dev-network

  # Create service with Fiber sender.
  sender:
    container_name: sender
    ports:
      - 3000:3000
    build:
      context: .
      dockerfile: Dockerfile-sender
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@sms-broker:5672/
    restart: always
    networks:
      - dev-network
    depends_on:
      - sms-broker

  # Create service with message consumer.
  consumer:
    container_name: consumer
    build:
      context: .
      dockerfile: Dockerfile-consumer
    environment:
      AMQP_SERVER_URL: amqp://guest:guest@sms-broker:5672/
    restart: always
    networks:
      - dev-network
    depends_on:
      - sender
      - sms-broker

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge
